
package prueba;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JMFC
 */

//Formulario de prueba para el componente Reloj Digital y su alarma.
public class PruebaRelojDigital extends javax.swing.JFrame {

    /**
     * Creates new form PruebaRelojDigital
     */
    public PruebaRelojDigital() {
        initComponents();
        setTitle("Reloj Digital");
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        relojDigital1 = new componente_reloj_digital.RelojDigital();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        relojDigital1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relojDigital1.setAlarmaActiva(true);
        relojDigital1.setAlarmaHora(20);
        relojDigital1.setAlarmaMensaje("Hora del evento.");
        relojDigital1.setAlarmaMinuto(32);
        relojDigital1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        relojDigital1.setFormato24h(true);
        relojDigital1.addAlarmaListener(new componente_reloj_digital.AlarmaListener() {
            public void suenaAlarma(componente_reloj_digital.AlarmaEvent evt) {
                relojDigital1SuenaAlarma(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(relojDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(relojDigital1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //En este método proporcionado por la interfaz de nuestro componente, implemento la acción que quiero que realice el componente cuando se dipare el evento.
    private void relojDigital1SuenaAlarma(componente_reloj_digital.AlarmaEvent evt) {//GEN-FIRST:event_relojDigital1SuenaAlarma
            JOptionPane.showMessageDialog(null, relojDigital1.getAlarmaMensaje(), "Alarma",JOptionPane.INFORMATION_MESSAGE);       //Muestro en un JOptionPane el mensaje que me han pasado por la propiedad AlarmaMensaje.    
    }//GEN-LAST:event_relojDigital1SuenaAlarma

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaRelojDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaRelojDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaRelojDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaRelojDigital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaRelojDigital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componente_reloj_digital.RelojDigital relojDigital1;
    // End of variables declaration//GEN-END:variables
}
